stages:
  - test

before_script:
  # Update package lists
  - sudo apt-get update
  # Install necessary utilities
  - sudo apt-get install -y wget zip unzip curl software-properties-common
  # Download and install Node.js
  - curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  # Verify Node.js and npm installation
  - node -v
  - npm -v
  # Download the BrowserStack binary file
  - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
  # Unzip the BrowserStack Local binary file
  - unzip BrowserStackLocal-linux-x64.zip
  # Run the file with the access key
  - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon start
  # Install all Chrome-related libraries in order to run puppeteer
  - sudo apt-get update
  - sudo apt-get install -y wget unzip libnss3-dev libglib2.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0
  # Install Node.js dependencies including http-server
  - npm install --save -dev puppeteer mocha chai http-server

run_tests:
  stage: test
  script:
    - echo "Testing the CI environment setup"
    # Start the server in the background; serve files from the 'html-examples' directory
    - ./node_modules/.bin/http-server ./html-examples -p 8080 &
    # Wait a bit to ensure the server is up
    - sleep 5
    - npm test
    # - npm run ./tests/test-html-css.js
    # Stop the BrowserStack Local
    - ./BrowserStackLocal --key $BROWSERSTACK_ACCESS_KEY --daemon stop
