stages:
  - test

before_script:
   #Download the browserstack binary file
   - wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
   #For OS X systems, use the following command
   #- wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
   #Unzip the BrowserStack Local binary file
   - unzip BrowserStackLocal-linux-x64.zip
   #Run the file with your access key
   - ./BrowserStackLocal --key D87TqMzmpus7Fy2iePP4 --daemon start

test:
   script:
         - npm install
         - npm run test
         - ./BrowserStackLocal --key D87TqMzmpus7Fy2iePP4 --daemon stop