import { createIcon } from './Icon';

const iconNames = [
  '99-bus',
  'arrows',
  'art-palette',
  'atoms',
  'bagpipes',
  'beach-walk',
  'bike',
  'books',
  'briefcase',
  'calculator',
  'car',
  'cathedral',
  'chalkboard',
  'cliffs',
  'clock',
  'coffee',
  'coins',
  'cooking',
  'crest-book',
  'crest',
  'dragon-claw',
  'dragon-head',
  'email-sign',
  'film',
  'friends',
  'globe',
  'golf-tee',
  'golf',
  'gown',
  'graduation-scroll',
  'hand',
  'handshake',
  'hello-languages',
  'highland-cow',
  'key',
  'laptop',
  'lightbulb',
  'links',
  'location-pin',
  'lock',
  'mace',
  'medal',
  'meditation',
  'microscope',
  'mobile',
  'money',
  'mountains',
  'music',
  'nightclub',
  'number-1',
  'old-course-bridge',
  'people',
  'pie-chart',
  'pier',
  'plane',
  'play-button',
  'popper',
  'power-button',
  'pub',
  'quad',
  'rocket',
  'saints-sport',
  'salvator-tower',
  'science',
  'scotland',
  'seagull',
  'shortbread',
  'speech-bubble',
  'sport',
  'st-andrews-castle',
  'sunrise',
  'sunset',
  'taste',
  'teaching',
  'test-tubes',
  'thistle',
  'train',
  'trophy',
  'umbrella',
  'up-arrow',
  'waves',
  'weights',
  'west-sands',
  'your-union',
]

export default {
  title: 'Components/Icons',
  tags: ['autodocs'],
  render: ({ name, colour, size }) => {
    return createIcon({ name, colour, size });
  },
  argTypes: {
    name: {
      control: { type: 'select' },
      options: [...iconNames],
    },
    colour: {
      control: { type: 'select' },
      options: ['blue', 'burgundy', 'green', 'purple'],
    },
    size: {
      control: { type: 'select' },
      options: ['sm', 'md', 'lg', 'xl'],
    }
  }
}

export const Icon = {
  args: {
    name: '99-bus',
    colour: 'blue',
    size: 'md',
  }
}
